config/routes.rb
if Rails::VERSION::MAJOR >= 3
  RedmineApp::Application.routes.draw do
    resources :approval_items do
      collection do
        get :autocomplete_for_user
        get :card
      end
    end
    post '/issues/:issue_id/approvers' => 'approval_items#create'
    delete '/issues/:issue_id/approvers/:user_id' => 'approval_items#destroy'
    put '/issues/:issue_id/approvers/:user_id' => 'approval_items#update'
  end
else
  ActionController::Routing::Routes.draw do |map|
    map.resources :approval_items
    map.connect   'approval_item/autocomplete_for_user', :controller=> :approval_items, :action => :autocomplete_for_user, :conditions => {:method => :get}
    map.connect   'approval_item/card', :controller=> :approval_items, :action => :card, :conditions => {:method => :get}
  end
end

app/views/my/_approval_list_simple.html.haml
- issues.compact! if issues && issues.any?
- if issues && issues.any?
  %table{:class => "list issues"}
    %thead
      %tr
        %th
          = "#"
        %th
          = l(:field_project)
        %th
          = l(:label_theme)
        %th
          = l(:field_status)
        %th
          = l(:field_assigned_to)
        %th
          = l(:field_start_date)
        %th
          = l(:field_due_date)
    %tbody
      - for issue in issues
        %tr{:id => "issue-#{h(issue.id)}", :class => "hascontextmenu #{cycle('odd', 'even')} #{issue.css_classes}"}
          %td{:class => "id"}
            = check_box_tag("ids[]", issue.id, false, :style => 'display:none;', :id => nil) 
            = link_to issue.id, issue_path(issue) 
          %td{:class => "project"}
            = link_to_project(issue.project)
          %td{:class => "subject"}
            = link_to truncate(issue.subject, :length => 60), issue_path(issue)               
          %td{:class => "status"}
            = h issue.status
          %td
            = link_to_user(issue.assigned_to)
          %td
            = format_date(issue.start_date)
          %td
            = format_date(issue.due_date)
- else
  %p{:class => "nodata"}
    = l(:label_no_data)

app/views/my/_approve_list.html.haml
- allowed_status_ids = IssueStatus.where(id: Setting[:plugin_redmine_approval_page][:issue_not_approved_statuses]).map(&:id)
- approval_issues = ApprovalItem.where(user_id: User.current.id, approved: [nil, false]).map{|i| i.approval_issue if allowed_status_ids.include?(i.approval_issue.status_id)}.compact#map(&:approval_issue).compact

%h3
  = "Задачи на согласование"
  = " (#{approval_issues.count})"


= render :partial => 'approval_list_simple', :locals => { :issues => approval_issues, :allows => [:author, :assigned_to] }

app/views/my/approval_list_simple.html.haml
- if issues && issues.any? 
  %table{:class => "list issues"}
    %thead
      %tr
        %th
          = "#"
        %th
          = l(:field_project)
        %th
          = l(:label_theme)
        %th
          = l(:field_status)
        %th
          = l(:field_assigned_to)
        %th
          = l(:field_start_date)
        %th
          = l(:field_due_date)
    %tbody
      - for issue in issues
        %tr{:id => "issue-#{h(issue.id)}", :class => "hascontextmenu #{cycle('odd', 'even')} #{issue.css_classes}"}
          %td{:class => "id"}
            = check_box_tag("ids[]", issue.id, false, :style => 'display:none;', :id => nil) 
            = link_to issue.id, issue_path(issue) 
          %td{:class => "project"}
            = link_to_project(issue.project)
          %td{:class => "subject"}
            = link_to truncate(issue.subject, :length => 60), issue_path(issue)               
          %td{:class => "status"}
            = h issue.status
          %td
            = link_to_user(issue.assigned_to)
          %td
            = format_date(issue.start_date)
          %td
            = format_date(issue.due_date)
- else
  %p{:class => "nodata"}
    = l(:label_no_data)